### ISSUE TITLE
From Name not correct when lastname contains paranthesis ()

### ISSUE THREAD

**Issue by tofi86** [taqueci/redmine_mail_from#9]
I have the following configuration:

```
%f %l (via pagina-Ticketsystem) <redmine-no-reply@host.tld> ::: pagina-Ticketsystem <redmine-no-reply@host.tld>
```

When the user lastname contains parenthesis (e.g. Firstname: `External`, Lastname: `User (Company)`) the From is displayed as as `External User (Company via pagina-Ticketsystem)` in the Thunderbrid and Outlook GUI.

The  From Header in sourcecode is:

```
From: External User <redmine-no-reply@host.tld> (Company via pagina-Ticketsystem)
```

The wrong order of parts was reported in #8, but I would expect that the display name would be `External User (Company) (via pagina-Ticketsystem)`

Seems to be a bug with the replace algorithm?

**Comment by taqueci** [comment]
Hello, @tofi86

The issue is reproduced in my environment.
I'm not sure, but it may be caused by mail server.

I guess you can avoid it by using double quotations.
Please try as follows:

    "%f %l (via pagina-Ticketsystem)" <redmine-no-reply@host.tld> :: pagina-Ticketsystem <redmine-no-reply@host.tld>

**Comment by tofi86** [comment]
Hi @taqueci,

awesome, this works like a charm! And it also solves issue #8.

Can you probably add a phrase or two in the Readme file?
